### ISSUE TITLE
Timestamp / count don't always catch newlines? :(

### ISSUE THREAD

**Issue by ppannuto** [tock/tockloader#30]
Posting for later investigation, but a device printing like this:
```
        printf("\r");
        for (j=0; j<adv.dlen; j++) {
          printf("%02x", adv.data[j]);
        }
        printf("\n");
```
doesn't result in the timestamp / count option working, which is a bit surprising as I'd expect that lone '\n' at the end to make things happy

**Comment by ppannuto** [comment]
It also gets unhappy when corrupt (probably interpreted as serial control things) characters come through, resulting in an empty message:

```
[2018-05-27 17:41:24.914210] [ 80623] Disconnected. Attempting to reconnect
[2018-05-28 12:27:09.009476] [ 80624] ␀`␀F␀␀␅D�␀,␡��.&��~R�␀ ␀␀␀␄␀�␁␀␀ ␀�#@�␑��␂�␃␀␀Q���␀␄␞�␀@�␀␁o�"␀␁␀␀␀�␀Exception in thread rx:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyserial-3.2.1-py3.6.egg/serial/tools/miniterm.py", line 459, in reader
    text = transformation.rx(text)
  File "/Volumes/code/helena-project/tockloader/tockloader/bootloader_serial.py", line 726, in rx
    self.last = text[-1]
IndexError: string index out of range
```
